version: '3'

vars:
  PROJECT_NAME: vulcan-ci

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  lint:
    desc: Run clippy linter with warnings as errors
    cmds:
      - cargo clippy --workspace -- -D warnings

  fmt:
    desc: Format code with rustfmt
    cmds:
      - cargo fmt --all

  fmt-check:
    desc: Check if code is formatted correctly
    cmds:
      - cargo fmt --all -- --check

  check:
    desc: Fast compile check without building
    cmds:
      - cargo check --workspace

  test:
    desc: Run all tests
    cmds:
      - cargo test --workspace

  build:
    desc: Build the project in debug mode
    cmds:
      - cargo build --workspace

  release:
    desc: Build the project in release mode
    cmds:
      - cargo build --workspace --release

  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean

  all:
    desc: Format, lint, and build the project
    deps:
      - fmt
      - lint
      - build
    cmds:
      - echo "All checks passed!"

  ci:
    desc: Run CI checks (format check, lint, test, build)
    deps:
      - fmt-check
      - lint
      - test
      - build
    cmds:
      - echo "CI checks passed!"

  # Service run tasks
  run-api:
    desc: Run the API service
    cmds:
      - cargo run --package vulcan-api

  run-worker:
    desc: Run the Worker service
    cmds:
      - cargo run --package vulcan-worker

  run-worker-orchestrator:
    desc: Run the Worker Orchestrator service
    cmds:
      - cargo run --package vulcan-worker-orchestrator

  run-chain-parser:
    desc: Run the Chain Parser service
    cmds:
      - cargo run --package vulcan-chain-parser

  run-workflow-trigger-processor:
    desc: Run the Workflow Trigger Processor service
    cmds:
      - cargo run --package vulcan-workflow-trigger-processor

  # kind cluster tasks
  kind-up:
    desc: Create kind cluster with all services
    cmds:
      - kind create cluster --config kind-config.yaml
      - task: kind-build
      - kind load docker-image vulcan-worker-orchestrator:dev --name vulcan-ci
      - kind load docker-image vulcan-worker:dev --name vulcan-ci
      - kind load docker-image vulcan-worker-controller:dev --name vulcan-ci
      - kubectl apply -f k8s/00-namespace.yaml
      - kubectl apply -f k8s/
      - echo "Waiting for PostgreSQL..."
      - kubectl wait --namespace vulcan --for=condition=ready pod -l app=postgres --timeout=120s
      - diesel migration run
      - echo "Waiting for Worker Orchestrator..."
      - kubectl wait --namespace vulcan --for=condition=ready pod -l app=worker-orchestrator --timeout=120s
      - kubectl get all -n vulcan

  kind-down:
    desc: Delete the kind cluster
    cmds:
      - kind delete cluster --name vulcan-ci

  kind-build:
    desc: Build all Docker images for kind
    cmds:
      - docker build --build-arg SERVICE=vulcan-worker-orchestrator -t vulcan-worker-orchestrator:dev .
      - docker build -f Dockerfile.worker -t vulcan-worker:dev .
      - docker build --build-arg SERVICE=vulcan-worker-controller -t vulcan-worker-controller:dev .

  kind-load:
    desc: Rebuild images, reload into kind, and restart deployments
    cmds:
      - task: kind-build
      - kind load docker-image vulcan-worker-orchestrator:dev --name vulcan-ci
      - kind load docker-image vulcan-worker:dev --name vulcan-ci
      - kind load docker-image vulcan-worker-controller:dev --name vulcan-ci
      - kubectl rollout restart deployment/worker-orchestrator -n vulcan
      - kubectl rollout restart deployment/vulcan-worker -n vulcan
      - kubectl rollout restart deployment/worker-controller -n vulcan

  kind-load-orchestrator:
    desc: Rebuild and reload the orchestrator image
    cmds:
      - docker build --build-arg SERVICE=vulcan-worker-orchestrator -t vulcan-worker-orchestrator:dev .
      - kind load docker-image vulcan-worker-orchestrator:dev --name vulcan-ci
      - kubectl rollout restart deployment/worker-orchestrator -n vulcan

  kind-load-worker:
    desc: Rebuild and reload the worker image
    cmds:
      - docker build -f Dockerfile.worker -t vulcan-worker:dev .
      - kind load docker-image vulcan-worker:dev --name vulcan-ci
      - kubectl rollout restart deployment/vulcan-worker -n vulcan

  kind-load-controller:
    desc: Rebuild and reload the worker-controller image
    cmds:
      - docker build --build-arg SERVICE=vulcan-worker-controller -t vulcan-worker-controller:dev .
      - kind load docker-image vulcan-worker-controller:dev --name vulcan-ci
      - kubectl rollout restart deployment/worker-controller -n vulcan

  kind-status:
    desc: Show status of all resources in the vulcan namespace
    cmds:
      - kubectl get all -n vulcan

  kind-logs:
    desc: "Tail logs for a deployment (usage: task kind-logs -- worker-orchestrator)"
    cmds:
      - kubectl logs -f deployment/{{.CLI_ARGS}} -n vulcan

  # Database tasks
  db-reset:
    desc: Reset the database (delete PVC, restart postgres, run migrations)
    cmds:
      - kubectl delete pvc postgres-data -n vulcan --ignore-not-found
      - kubectl rollout restart deployment/postgres -n vulcan
      - kubectl wait --namespace vulcan --for=condition=ready pod -l app=postgres --timeout=120s
      - diesel migration run

  db-migrate:
    desc: Run pending database migrations
    cmds:
      - diesel migration run

  db-migrate-redo:
    desc: Redo the last migration
    cmds:
      - diesel migration redo

  db-psql:
    desc: Open psql shell to the database
    cmds:
      - kubectl exec -it deployment/postgres -n vulcan -- psql -U vulcan -d vulcan_ci

  # Integration test
  test-scaling:
    desc: Run the scaling integration test
    cmds:
      - bash scripts/test-scaling.sh
