version: '3'

vars:
  PROJECT_NAME: vulcan-ci

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  lint:
    desc: Run clippy linter with warnings as errors
    cmds:
      - cargo clippy -- -D warnings

  fmt:
    desc: Format code with rustfmt
    cmds:
      - cargo fmt

  fmt-check:
    desc: Check if code is formatted correctly
    cmds:
      - cargo fmt -- --check

  check:
    desc: Fast compile check without building
    cmds:
      - cargo check

  test:
    desc: Run all tests
    cmds:
      - cargo test

  build:
    desc: Build the project in debug mode
    cmds:
      - cargo build

  release:
    desc: Build the project in release mode
    cmds:
      - cargo build --release

  run:
    desc: Run the project
    cmds:
      - cargo run

  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean

  all:
    desc: Format, lint, and build the project
    deps:
      - fmt
      - lint
      - build
    cmds:
      - echo "✅ All checks passed!"

  ci:
    desc: Run CI checks (format check, lint, test, build)
    deps:
      - fmt-check
      - lint
      - test
      - build
    cmds:
      - echo "✅ CI checks passed!"

  # Database tasks
  db-up:
    desc: Start the PostgreSQL database
    cmds:
      - docker compose up -d
      - echo "Waiting for database to be ready..."
      - sleep 2
      - docker compose ps

  db-down:
    desc: Stop the PostgreSQL database
    cmds:
      - docker compose down

  db-reset:
    desc: Reset the database (stop, remove volume, start fresh)
    cmds:
      - docker compose down -v
      - docker compose up -d
      - echo "Waiting for database to be ready..."
      - sleep 2
      - diesel migration run

  db-migrate:
    desc: Run pending database migrations
    cmds:
      - diesel migration run

  db-migrate-redo:
    desc: Redo the last migration
    cmds:
      - diesel migration redo

  db-psql:
    desc: Open psql shell to the database
    cmds:
      - docker compose exec postgres psql -U vulcan -d vulcan_ci
